### ISSUE TITLE
How to connect to other nodes

### ISSUE THREAD

**Issue by robinchesterman** [AlexandreDaSilva/DgraphNet#1]
Something is not clear to me.

How can I use this client to connect entities to other entities? e.g.

Presuming I've added this:
```
    var steve = new Person {
      xid : "_:1"
    }_
```

And I want to add another person with Steve as a friend:
```
   var alice = new Person() {
     xid: "_:2"
     BestFriend : new Person {
        xid: "_:1"
     }
  } 
```

This doesnt add Steve as a Friend for Alice. I thought `xid` was a good way to approach this since, from the docs "As of version 0.8 Dgraph doesn’t natively support such external IDs as node identifiers. Instead, external IDs can be stored as properties of a node with an xid edge."

**Comment by AlexandreDaSilva** [comment]
Hi! 
In Dgraph, each node natively has an unique identifier (named "uid"). 

The "xid" predicate is a naming convention used when you deal with external data sources, whose entities may themselves have an identifier (an "external id"). In this case, your entity will have a uid in Dgraph, but you can use a "xid" predicate to indicate its external id. Again, it's just a naming convention! You could call this predicate "externalId", "twitterId", etc.

In your case, to create a link between two entities in Dgraph, you must use the uid predicate (see https://docs.dgraph.io/mutations/#referencing-existing-nodes).

**Comment by robinchesterman** [comment]
Thanks for getting back so quickly!

I think my problem is that I won't know the uid at insert time - indeed the object may not yet exist. I just have the xid as a URI.

**Comment by AlexandreDaSilva** [comment]
You're welcome!

When you want to reference a node before its creation, Dgraph has the concept of "blank nodes": a temporary identifier local to a mutation (https://docs.dgraph.io/mutations/#blank-nodes-and-uid).

Could you post a sample of your code?

**Comment by robinchesterman** [comment]
Thanks - sorry for the delay getting back.

I'm importing data from another database into DGraph - it's to do with case law, where each case may cite other cases. All of my cases already have IDs. The JSON could be structured like so:
```
{
  "Title" : "Smith v Jones",
  "Id" : 1,
   CitedCases: [
      { "Id" : 2 }
   ]
}
```
```
{
  "Title" : "Peters v Jackson",
  "Id" : 2
}
```
Modelled like this:
```
public class CaseDocument {
  public string Name { get; set; }
  public string Id { get; set; }
  public List<CaseDocument> CitedCases { get; set; } 
}
```

Attempting to add case with Id 1:

```
var channel = new Channel(ConfigurationManager.AppSettings["DGraphEndpoint"], ChannelCredentials.Insecure);
            var connection = new DgraphConnection(channel);
            var pool = new DgraphConnectionPool().Add(connection);
            var doc = new CaseDocument
            {
                Title = "Smith v Jones",
                Id = 1,
                CitedCases = new List<CaseDocument> {
                   new CaseDocument {
                        Id= 2
                   }
                }
            };
            var client = new DgraphNetClient(pool);
            using (var txn = client.NewTransaction())
            {
                var json = JsonConvert.SerializeObject(doc );
                var mu = new Mutation { SetJson = ByteString.CopyFromUtf8(json) };
                txn.Mutate(mu);
                txn.Commit();
            }
````

So you see, when making the first transaction, I don't yet know anything about case #2 except an Id from my existing database. Other data for the case could/will get imported in the same way at a later time.

Does that make sense?

**Comment by robinchesterman** [comment]
I solved it by querying in every instance for an existing node by my ID, and creating a new one if it didn't existing and passing the new uid into the model.
